# Module 2 Graded Quiz


#### 1.Use the EDHEC Hedge Fund Indices data set that we used in the lab assignment as well as in the previous week’s assignments. Load them into Python and perform the following analysis based on data since 2000 (including all of 2000): What was the Monthly Parametric Gaussian VaR at the 1% level (as a +ve number) of the Distressed Securities strategy?

In [23]:
import pandas as pd
import numpy as np
import edhec_risk_kit as erk


%load_ext autoreload
%autoreload 2
%matplotlib inline

# obtener rentabilidades de los fondos
hfi = erk.get_hfi_returns()

# calcular el VaR Gaussian of the Distressed Securities strategy
erk.var_gaussian(hfi["2000":], level=1)



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Convertible Arbitrage     0.034845
CTA Global                0.050336
Distressed Securities     0.031430
Emerging Markets          0.058070
Equity Market Neutral     0.014772
Event Driven              0.030853
Fixed Income Arbitrage    0.019519
Global Macro              0.024619
Long/Short Equity         0.039420
Merger Arbitrage          0.015355
Relative Value            0.021605
Short Selling             0.102130
Funds Of Funds            0.029385
dtype: float64

#### 2.Use the same data set at the previous question. What was the 1% VaR for the same strategy after applying the Cornish-Fisher Adjustment?

In [24]:
erk.var_gaussian(hfi["2000":], level=1, modified=True)

Convertible Arbitrage     0.103666
CTA Global                0.046643
Distressed Securities     0.049669
Emerging Markets          0.086796
Equity Market Neutral     0.041432
Event Driven              0.045732
Fixed Income Arbitrage    0.066479
Global Macro              0.022786
Long/Short Equity         0.051381
Merger Arbitrage          0.021282
Relative Value            0.048985
Short Selling             0.098323
Funds Of Funds            0.048793
dtype: float64

#### 3.Use the same dataset as the previous question. What was the Monthly Historic VaR at the 1% level (as a +ve number) of the Distressed Securities strategy?

In [25]:
# obtener rentabilidades de los fondos
hfi = erk.get_hfi_returns()

# calcular el VaR Gaussian of the Distressed Securities strategy
erk.var_historic(hfi["2000":], level=1)



Convertible Arbitrage     0.031674
CTA Global                0.050938
Distressed Securities     0.042642
Emerging Markets          0.065496
Equity Market Neutral     0.019800
Event Driven              0.038540
Fixed Income Arbitrage    0.030748
Global Macro              0.022632
Long/Short Equity         0.045060
Merger Arbitrage          0.022654
Relative Value            0.021788
Short Selling             0.107684
Funds Of Funds            0.027200
dtype: float64

#### 4. Next, load the 30 industry return data using the erk.get_ind_returns() function that we developed during the lab sessions. For purposes of the remaining questions, use data during the 5 year period 2013-2017 (both inclusive) to estimate the expected returns as well as the covariance matrix. To be able to respond to the questions, you will need to build the MSR, EW and GMV portfolios consisting of the “Books”, “Steel”, "Oil", and "Mines" industries. Assume the risk free rate over the 5 year period is 10%.

What is the weight of Steel in the EW Portfolio?

In [51]:
import numpy as np

l = ["Books", "Steel", "Oil", "Mines"]

ind = erk.get_ind_returns()
er = erk.annualize_rets(ind["2013":"2017"], 12)[l]
cov = ind["2013":"2017"].cov().loc[l,l]

n = er.shape[0]
w_ew = np.repeat(1/n, n)
r_ew = erk.portfolio_return(w_ew, er)
vol_ew = erk.portfolio_vol(w_ew, cov)

w_ew

array([0.25, 0.25, 0.25, 0.25])

#### 5.What is the weight of the largest component of the MSR portfolio?

In [56]:
# Maximum Sharpe Ratio
erk.msr(0.1, er, cov).max()


0.9999999999999953

#### 6. Which of the 4 components has the largest weight in the MSR portfolio?

In [59]:
l[erk.msr(0.1, er, cov).argmax()]

'Steel'

#### 7. How many of the components of the MSR portfolio have non-zero weights? 

In [67]:
erk.msr(0.1, er, cov)


array([4.51375048e-15, 1.00000000e+00, 1.40512602e-16, 0.00000000e+00])

#### 8. What is the weight of the largest component of the GMV portfolio?

In [69]:
erk.gmv(cov).max()

0.47702487032166246

#### 9. Which of the 4 components has the largest weight in the GMV portfolio?

In [71]:
l[erk.gmv(cov).argmax()]

'Books'

#### 10.  How many of the components of the GMV portfolio have non-zero weights? 

In [74]:
erk.gmv(cov)

array([4.77024870e-01, 4.33680869e-19, 4.34112024e-01, 8.88631053e-02])

#### 11. Assume two different investors invested in the GMV and MSR portfolios at the start of 2018 using the weights we just computed. Compute the annualized volatility of these two portfolios over the next 12 months of 2018? (Hint: Use the portfolio_vol code we developed in the lab and use ind[“2018”][l].cov() to compute the covariance matrix for 2018, assuming that the variable ind holds the industry returns and the variable l holds the list of industry portfolios you are willing to hold. Don’t forget to annualize the volatility)

What would be the annualized volatility over 2018 using the weights of the MSR portfolio?

In [90]:

erk.portfolio_vol(erk.gmv(cov), ind["2018"][l].cov().loc[l,l])* 12**0.5 * 100

18.973734511535802

In [91]:
erk.portfolio_vol(erk.msr(0.1, er, cov), ind["2018"][l].cov().loc[l,l])* 12**0.5 * 100

21.983988181484136

#### 12. What would be the annualized volatility over 2018 using the weights of the GMV portfolio? (Reminder and Hint: Use the portfolio_vol code we developed in the lab and use ind[“2018”][l].cov() to compute the covariance matrix for 2018, assuming that the variable ind holds the industry returns and the variable l holds the list of industry portfolios you are willing to hold. Don’t forget to annualize the volatility)

In [92]:
erk.portfolio_vol(erk.gmv(cov), ind["2018"][l].cov().loc[l,l])* 12**0.5 * 100

18.973734511535802